title: Iqbal Hazri
description: My personal website and blog
markdown: kramdown

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  title: ":title - page :num"
  permalink: /blog/page/:num/
  trail:
    before: 2
    after: 2
  sort_field: "date"
  sort_reverse: true